### ISSUE TITLE
Could not load NIB in bundle when using CocoaPods

### ISSUE THREAD

**Issue by voidmorn** [tapstream/tapstream-sdk#61]
Hi,
I used CocoaPods to import tapstream sdk and WoM sdk.
I add 
`pod 'Tapstream', '~> 2.9.3'`
`pod 'TapstreamWOM', '~> 2.9.3'`
in my Podfile and installed.

But when I try to show offer in app:
`TSWordOfMouthController *wom = [TSTapstream wordOfMouthController];
    
    [wom offerForInsertionPoint:@"womtest" result:^(TSOffer *offer) {
        if(offer) {
            [wom showOffer:offer parentViewController:self];
        }
    }];

The app crashed and showed the tip:
Uncaught exception: Could not load NIB in bundle: 'NSBundle </Users/lin/Library/Developer/CoreSimulator/Devices/B17F1175-5784-4269-8C67-BC3803D7400F/data/Containers/Bundle/Application/747219C7-AB1B-4733-AAC2-2ED8CDBFB537/XXXFree.app> (loaded)' with name 'TSOfferView'

Following this tip, I found that your released zip file contains the "TSOfferView.xib" while it is not included by CocoaPods.
Is there some way to fix it in CocoaPods?

**Comment by adambard** [comment]
Whoops, sorry about that. I've just published a new release (2.9.4) that should fix this issue, can you try that out and confirm that it resolves this issue (or at least that TSOfferView.xib" is present)?

**Comment by voidmorn** [comment]
@adambard 
Sorry, I can't install TapstreamWOM 2.9.4 on CocoaPods. Tapstream SDK is upgrade but TapstreamWOM not. This problem is not fixed.
![image](https://cloud.githubusercontent.com/assets/3390634/9347734/27dd4758-4660-11e5-9c97-05bb52bfd4df.png)

**Comment by adambard** [comment]
My apologies again! I've confirmed that the push to cocoapods went through now, sorry for wasting your time.

**Comment by voidmorn** [comment]
@adambard 
Maybe...You need fix some code like that:https://github.com/bennyguitar/CollapseClick/commit/f023656bcc70fdecad4c6dd189936f9e90c23b29

The new version can't build successfully.

![image](https://cloud.githubusercontent.com/assets/3390634/9349947/c154fe12-467e-11e5-8291-b5d8d98268f6.png)

**Comment by JeanLebrument** [comment]
Same problem here

**Comment by adambard** [comment]
Right, I think I see the issue. Thanks for your patience, I've pushed a fix for that to master.

Could I get you to test that out using a git reference in your Podspec and spare me botching another release?

```
pod 'TapstreamWOM', :git => 'https://github.com/tapstream/tapstream-sdk.git', :branch => 'master'
```

**Comment by voidmorn** [comment]
@adambard Yeah, it works now.

**Comment by adambard** [comment]
Perfect, thanks a lot for your help. I've just pushed the 2.9.5 release, you can remove the git reference at your leisure.
